global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["host.docker.internal:9100"]

  - job_name: "process"
    static_configs:
      - targets: [ "process-exporter:9256" ]

  - job_name: "opera"
    metrics_path: '/debug/metrics/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:6060' ]